os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.9.1"
jdk:
  - oraclejdk8
cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.yarn-cache
    - node_modules
    - $HOME/app/
before_cache:
  - rm -rf $HOME/app/*.war $HOME/app/target/ $HOME/app/target $HOME/app/build $HOME/app/node_modules/generator-jhipster
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
    # - JHIPSTER=app-default-from-scratch PROFILE=prod RUN_APP=0
    # - JHIPSTER=app-gradle PROTRACTOR=1
    - JHIPSTER=app-mysql PROFILE=prod PROTRACTOR=1
    - JHIPSTER=app-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    # - JHIPSTER=app-social-websocket PROTRACTOR=1
    # - JHIPSTER=app-cassandra
    # - JHIPSTER=app-hazelcast-cucumber
    # - JHIPSTER=app-mongodb
    # - JHIPSTER=app-oauth2
    # - JHIPSTER=app-jwt
    # - JHIPSTER=app-mariadb-kafka
    # - JHIPSTER=app-gateway-eureka
    # - JHIPSTER=app-microservice-eureka
    # - JHIPSTER=app-gateway-consul
    # - JHIPSTER=app-microservice-consul
    # - JHIPSTER=app-gateway-uaa

before_install:
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add yo bower gulp-cli
  # Check version
  - java -version
  - git --version
  - node -v
  - npm -v
  - yarn --version
  - bower -v
  - yo --version
  - gulp -v
  - docker version
  - docker-compose version
install:
  - cd "$TRAVIS_BUILD_DIR"/
  - yarn install
  - yarn link
  - yarn run test
script:
  - $JHIPSTER_SCRIPTS/01-generate-entities.sh
  - $JHIPSTER_SCRIPTS/02-generate-project.sh
  - $JHIPSTER_SCRIPTS/03-docker-compose.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
  - $JHIPSTER_SCRIPTS/06-sonar.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/479b810ad42c816679fb
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
