#
# Copyright 2013-2018 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    JH_PROFILE: dev
    JH_RUN_APP: 1
    JH_PROTRACTOR: 0
    JH_LIB_REPO: https://github.com/jhipster/jhipster.git
    JH_LIB_BRANCH: release
    JH_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
    JH_GEN_BRANCH: release
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JH_DISABLE_WEBPACK_LOGS: true
    JH_SCRIPTS: $BUILD_REPOSITORY_LOCALPATH/test-integration/scripts

  strategy:
    maxParallel: 10
    matrix:
      ngx-default:
        JH_APP: ngx-default
        JH_PROFILE: prod
        JH_PROTRACTOR: 1
      ngx-psql-es-noi18n:
        JH_APP: ngx-psql-es-noi18n
        JH_PROFILE: prod
        JH_PROTRACTOR: 1
      ngx-gradle-fr:
        JH_APP: ngx-gradle-fr
        JH_PROFILE: prod
        JH_PROTRACTOR: 1
      ngx-h2mem-ws-nol2:
        JH_APP: ngx-h2mem-ws-nol2

  steps:
  #----------------------------------------------------------------------
  # Install all tools and check configuration
  #----------------------------------------------------------------------
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
    displayName: 'TOOLS: install Node.js'
  - script: |
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      sudo apt update
      sudo apt install google-chrome-stable
    displayName: 'TOOLS: install google-chrome-stable'
  - script: sudo npm install -g npm
    displayName: 'TOOLS: update NPM'
  - bash: $(JH_SCRIPTS)/01-display-configuration.sh
    displayName: 'TOOLS: display configuration'
  - bash: $(JH_SCRIPTS)/02-display-tools.sh
    displayName: 'TOOLS: display installed tools'
  - bash: $(JH_SCRIPTS)/03-system.sh
    displayName: 'TOOLS: configure tools installed by the system'
  #----------------------------------------------------------------------
  # Install JHipster and generate project+entities
  #----------------------------------------------------------------------
  - bash: $(JH_SCRIPTS)/10-install-jhipster.sh
    displayName: 'GENERATION: install JHipster'
  - bash: $(JH_SCRIPTS)/11-generate-entities.sh
    displayName: 'GENERATION: entities'
  - bash: $(JH_SCRIPTS)/12-generate-project.sh
    displayName: 'GENERATION: project'
  - bash: $(JH_SCRIPTS)/13-replace-version-generated-project.sh
    displayName: 'GENERATION: replace version in generated project'
  #----------------------------------------------------------------------
  # Launch tests
  #----------------------------------------------------------------------
  - bash: $(JH_SCRIPTS)/20-docker-compose.sh
    displayName: 'TESTS: Start docker-compose containers'
  - bash: $(JH_SCRIPTS)/21-tests-backend.sh
    displayName: 'TESTS: backend'
  - bash: $(JH_SCRIPTS)/22-tests-frontend.sh
    displayName: 'TESTS: frontend'
  - bash: $(JH_SCRIPTS)/23-package.sh
    displayName: 'TESTS: packaging'
  - bash: $(JH_SCRIPTS)/24-tests-e2e.sh
    displayName: 'TESTS: End-to-End'
