version: 2
jobs:
  build:
    machine:
      node:
        version: 8.9.4
      environment:
        PATH: "${PATH}:${HOME}/.yarn/bin:${PATH}"
    environment:
      - JHIPSTER_TRAVIS: /home/circleci/generator-jhipster/travis
      - JHIPSTER_SAMPLES: /home/circleci/generator-jhipster/travis/samples
      - JHIPSTER_SCRIPTS: /home/circleci/generator-jhipster/travis/scripts
      - JHIPSTER_DEPENDENCIES_REPO: https://github.com/jhipster/jhipster-dependencies.git
      - JHIPSTER_DEPENDENCIES_BRANCH: release
      - JHIPSTER_LIB_REPO: https://github.com/jhipster/jhipster.git
      - JHIPSTER_LIB_BRANCH: release
      - JHIPSTER_REPO: https://github.com/jhipster/generator-jhipster.git
      - JHIPSTER_BRANCH: release
    working_directory: ~/generator-jhipster
    steps:
      - checkout
      # See https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
      - run:
          name: Interpolating Environnement Variables
          command: |
            echo 'export TRAVIS_REPO_SLUG=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
            echo 'export TRAVIS_BUILD_DIR=$HOME/$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run:
          name: Check variables
          command: |
            java -version
            node -v
            docker version
            echo $PATH
            echo $HOME
            echo $JHIPSTER_TRAVIS
            echo $JHIPSTER_SAMPLES
            echo $JHIPSTER_SCRIPTS
            echo $JHIPSTER_DEPENDENCIES_REPO
            echo $JHIPSTER_DEPENDENCIES_BRANCH
            echo $JHIPSTER_LIB_REPO
            echo $JHIPSTER_LIB_BRANCH
            echo $JHIPSTER_REPO
            echo $JHIPSTER_BRANCH
            echo $TRAVIS_REPO_SLUG
            echo $TRAVIS_BUILD_DIR

      - run:
          name: Install last version of Docker
          command: |
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
            docker version
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose version
      - run:
          name: Install Yarn, then yo, bower and gulp-cli
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH=$HOME/.yarn/bin:$PATH
            echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
            yarn -v
            yarn global add yo bower gulp-cli
      - run:
          name: Check version
          command: |
            node -v
            java -version
            yarn -v
            git version
            docker version
            docker-compose version
      - run:
          name: Installation
          command: |
            "$JHIPSTER_SCRIPTS"/00-install-jhipster.sh
