version: 2
jobs:
  build:
    environment:
      - FOO: "bar"
      - JHIPSTER_TRAVIS: "${HOME}/generator-jhipster/travis"
      - JHIPSTER_SAMPLES: "${HOME}/generator-jhipster/travis/samples"
      - JHIPSTER_SCRIPTS: "${HOME}/generator-jhipster/travis/scripts"
    working_directory: ~/generator-jhipster
    machine:
      environment:
        PATH: "${PATH}:${HOME}/.yarn/bin:${PATH}"
    steps:
      - checkout
      - run:
          name: check
          command: |
            docker version
            echo $PATH
            echo $JHIPSTER_TRAVIS
            echo $JHIPSTER_SAMPLES
            echo $JHIPSTER_SCRIPTS
            echo $HOME
            echo $FOO
            echo "$FOO"
      - run: sudo service docker stop
      - run:
          name: Install last version of Docker
          command: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > docker-compose
            sudo mv docker-compose /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH=$HOME/.yarn/bin:$PATH
            echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
            yarn -v
            yarn global add yo bower gulp-cli
      - run:
          name: Check version
          command: |
            node -v
            java -version
            yarn -v
            git version
            docker version
            docker-compose version
      - run:
          name: Installation
          command: |
            sh "$JHIPSTER_SCRIPTS"/00-install-jhipster.sh
